### ISSUE TITLE
Minimum Ballance

### ISSUE THREAD

**Issue by eugjr** [enarjord/passivbot_binance_isolated_margin_legacy#2]
There is a miniminal needed amount to bot proper works? Adn which timeframe it uses? 5min, 30min?

I'm with 0.001BTC on margin wallet, leverage set at 3x, and double checked "margin enabled" on API settings, and also double checked the ccxt and python-binance install with no errors on cmd.
The bot is running but didn't opened any positions so far. On cmd I can see it's running, as it displays the working status properly: "Margin update balance", margin updating my trades DASH/BTC etc, margin updating open orders", but didn't create an order so far.

The settings.json is edit with the following pairs:
"quot": "BTC",
    "coins_long": [
        "BNB",
	"DASH",
        "EOS",  
        "ETH",
        "NEO",
        "TRX"

    ],
    "coins_shrt": [
        "DASH",
        "EOS",  
        "ETH",
        "NEO",
        "TRX"

Thanks for your help and patience.

**Comment by enarjord** [comment]
yes, there is a de facto minimum balance

with default settings, it will try to make bids and asks with account_equity * 0.0135, which in your case is 0.0000135 BTC per trade

binance minimum for pairs quoted in BTC is 0.0001 BTC

that is why it makes no orders, because they are too small

i just updated vwap.py to set long/short quote amount to binance's minimum in case the balance is too low

replace vwap.py and it should work for you now

however, it will not perform optimally with so low balance

**Comment by enarjord** [comment]
"Adn which timeframe it uses? 5min, 30min?"

it doesn't use candles at all

it listens to binance websocket partial book depth stream, updated once per second per symbol

emas are calculated second by second

**Comment by eugjr** [comment]
Thank you for the code update. I've increased the wallet position to ~75USD and it started the trades.
I'll study the code and try to learn from ti. 

Do you think it is possible to run a similar code in the binance futures?

**Comment by enarjord** [comment]
yes it should be possible to port this to binance futures

**Comment by eugjr** [comment]
In the settings we have the parameter "profit_pct": 0.0025 value. This % value is already discounted from fees, or I shoukd adjust it like fee%+profit % desired? On the code I see a self.fee = 0.99925 variable, so thats why I've asked.
Also regarding fees and BNB, the param "bnb_buffer": 50.3, the value is the max qty the bot will try to long to reach/keep VIP lvl?

Thanks

**Comment by enarjord** [comment]
no, "profit_pct": 0.0025 is not already discounted from fees.

say paying fees with bnb is enabled, you were the maker and vip level == 1,
then in order to break even you need profit_pct of ~0.00135

1 / (1 - 0.0675 * 0.01)**2 == 1.0013513681062263

in order to make at least 0.1% per position exit, you need profit_pct of at least 0.00235

1.001 / (1 - 0.0675 * 0.01)**2 == 1.0023527194743325

if you set profit_pct lower than 0.0013, you risk trading at a loss for some market pairs

the self.fee = 0.99925 in commons.py is used only for approximating a conversion cost between coins, for purposes of representing any coin amount in terms of any other coin

this is used in accounting, not in trading

the param "bnb_buffer": 50.3 is the min amount bnb to keep. it tells the bot to sell max(0.0, 50.3 - bnb_balance)

if bnb balance is 0, it may take some time for it to accumulate 50

if your volume is nowhere near enough to qualify for a particular vip status, you can adjust the bnb_buffer down

the 0.3 extra is for fees and interest paid with bnb

**Comment by eugjr** [comment]
Thank you so much, really helped me to set it up. 
If you want implement some functions on binance future trades please let me know, I have some trading strategies to be tested on automation there, I'll try to help implement it if you wish.

Thanks

**Comment by enarjord** [comment]
you are welcome

and thank you for trying out the bot and for your questions and comments
